import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";
import { SessionProvider } from "next-auth/react";
import gridImage from "@/app/grid-bg2.png";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-slate-50 ${geistMono.variable} antialiased font-Inter  `}
      >
        <SessionProvider>
          <Navbar />
          <div className="relative min-h-screen">
            <Image
              className="absolute right-8 -top-32 -z-10  "
              src={gridImage}
              alt="grid img"
            />
            {children}
          </div>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
